name: Deploy Github Pages
on: [push]
  # workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: install dotnet v6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x.x'
