name: Deploy GitHub Pages
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository 1
        uses: actions/checkout@v6

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        
    
