name: test

on :
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 4.x.x
